name: Drip
description: A coffee journal
twitter_username: msteenhagen

# url: http://msteenhagen.github.io/coffee
url: http://127.0.0.1:4000
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
pygments: true
paginate: 5

navigation:
 - title: Coffee journal
   url: /index.html
 - title: About
   url: /about.html
 - title: Map
   url: /map.html